language: php
php:
  - '7.0'

before_script:
  - composer install

script:
  - vendor/bin/parallel-lint --exclude vendor .
  - vendor/bin/phpunit --configuration tests/phpunit.xml --coverage-clover=coverage.xml
  - vendor/bin/phpstan analyse src tests --level=4

after_success:
  - bash <(curl -s https://codecov.io/bash)
